stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "minhafacomp-${CI_COMMIT_REF_NAME}"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - |
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
        PORT=4012
      elif [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
        PORT=4001
      fi
      docker stop "$IMAGE_NAME" || true
      docker rm "$IMAGE_NAME" || true
      docker build --build-arg BRANCH="$CI_COMMIT_REF_NAME" -t "$IMAGE_NAME" .
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "dev"'

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - |
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
        PORT=4012
      elif [ "$CI_COMMIT_REF_NAME" == "dev" ]; then
        PORT=4001
      fi
      docker run -d --network minhafacomp-network --name "$IMAGE_NAME" -p "$PORT:$PORT" "$IMAGE_NAME"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_REF_NAME == "dev"'